---
all:
  vars:
  hosts:
  children:
    logstash:
      hosts:
        elk-tbsp03-logstash01:
          ansible_host: 10.123.144.211
        elk-tbsp03-logstash02:
          ansible_host: 10.123.144.212
